### ISSUE TITLE
Can't edit entities owned by microservice through gateway with oauth in place (keycloak) when generated with khipster 

### ISSUE THREAD

**Issue by andrzej-polanowski-emerge** [jhipster/jhipster-kotlin#255] opened 2020-08-19 06:47 UTC
## Overview of the issue
Can't edit entities owned by microservice through gateway with oauth in place (keycloak) when generated with khipster (but it works great with jhipster)

## Motivation for or Use Case
need to have oauth in microservices setup

## Reproduce the error
create gateway & microservice app, add entity (or two in relation) to the microservice & 1 entity for the gateway (see attached jdl file)
[app.jdl.gz](https://github.com/jhipster/jhipster-kotlin/files/5094473/app.jdl.gz)

.
Launch default keycloak docker image, launch jhipster registry docker image, launch mvnw for gateway & microservice.
I'm able to log in into the gateway, abe to see entity owned by gateway, but not able to see entity for the microservice.

## KHipster Version(s)
generator-jhipster-kotlin
6.10.1
-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by julillosamaral** [comment] 2020-12-06 19:19
I think I just reported the same problem. Did you find a workaround for this?

Thanks

**Comment by julillosamaral** [comment] 2020-12-06 19:58
Attaching some logs of what my issue is, I'm debugging the app and the internals of springboot so I can find it out! Any help is welcomed :D

```----------------------------------------------------------
Application 'products' is running! Access URLs:
Local:      http://localhost:8081/
External:   http://192.168.2.100:8081/
Profile(s): dev,swagger
----------------------------------------------------------
2020-12-06 16:51:12.170 DEBUG 9808 --- [  restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'configserver.status' in PropertySource 'bootstrapProperties-file:central-config/localhost-config/application.yml' with value of type String
2020-12-06 16:51:12.170  INFO 9808 --- [  restartedMain] com.works.app.ProductsApp                : ----------------------------------------------------------
    Config Server:  Connected to the JHipster Registry running in Docker
----------------------------------------------------------
2020-12-06 16:52:17.511  INFO 9808 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-12-06 16:52:17.511 DEBUG 9808 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Detected StandardServletMultipartResolver
2020-12-06 16:52:17.511 DEBUG 9808 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Detected AngularCookieLocaleResolver
2020-12-06 16:52:17.531 DEBUG 9808 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
2020-12-06 16:52:17.531  INFO 9808 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 20 ms
2020-12-06 16:52:17.571 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/products'; against '/h2-console/**'
2020-12-06 16:52:17.573 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 1 of 13 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2020-12-06 16:52:17.576 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 2 of 13 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
2020-12-06 16:52:17.583 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 3 of 13 in additional filter chain; firing Filter: 'HeaderWriterFilter'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 4 of 13 in additional filter chain; firing Filter: 'LogoutFilter'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', GET]
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/products'; against '/logout'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', POST]
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /api/products' doesn't match 'POST /logout'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', PUT]
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /api/products' doesn't match 'PUT /logout'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'GET /api/products' doesn't match 'DELETE /logout'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 5 of 13 in additional filter chain; firing Filter: 'OAuth2AuthorizationRequestRedirectFilter'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/products'; against '/oauth2/authorization/{registrationId}'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 6 of 13 in additional filter chain; firing Filter: 'BearerTokenAuthenticationFilter'
2020-12-06 16:52:17.588 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 7 of 13 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
2020-12-06 16:52:17.589 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 8 of 13 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
2020-12-06 16:52:17.592 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 9 of 13 in additional filter chain; firing Filter: 'AnonymousAuthenticationFilter'
2020-12-06 16:52:17.593 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Populated SecurityContextHolder with anonymous token: 'org.springframework.security.authentication.AnonymousAuthenticationToken@5055b7be: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 192.168.2.100; SessionId: null; Granted Authorities: ROLE_ANONYMOUS'
2020-12-06 16:52:17.593 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 10 of 13 in additional filter chain; firing Filter: 'OAuth2AuthorizationCodeGrantFilter'
2020-12-06 16:52:17.597 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 11 of 13 in additional filter chain; firing Filter: 'SessionManagementFilter'
2020-12-06 16:52:17.597 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 12 of 13 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
2020-12-06 16:52:17.597 DEBUG 9808 --- [  XNIO-1 task-1] o.s.security.web.FilterChainProxy        : /api/products?cacheBuster=1607284337298 at position 13 of 13 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
2020-12-06 16:52:17.599 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/products'; against '/authorize'
2020-12-06 16:52:17.599 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/products'; against '/api/auth-info'
2020-12-06 16:52:17.600 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/api/products'; against '/api/**'
2020-12-06 16:52:17.600 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /api/products?cacheBuster=1607284337298; Attributes: [authenticated]
2020-12-06 16:52:17.600 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@5055b7be: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 192.168.2.100; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
2020-12-06 16:52:17.616 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@52593ac4, returned: -1
2020-12-06 16:52:17.634 DEBUG 9808 --- [  XNIO-1 task-1] o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=2020-12-06T19:52:17.629772Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 192.168.2.100; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]
2020-12-06 16:52:17.652 DEBUG 9808 --- [  XNIO-1 task-1] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [com.works.app.repository.CustomAuditEventRepository.add]: PROPAGATION_REQUIRES_NEW,ISOLATION_DEFAULT
2020-12-06 16:52:17.656 DEBUG 9808 --- [  XNIO-1 task-1] o.s.orm.jpa.JpaTransactionManager        : Opened new EntityManager [SessionImpl(625374968<open>)] for JPA transaction
2020-12-06 16:52:17.671 DEBUG 9808 --- [  XNIO-1 task-1] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@10d3e8e9]
2020-12-06 16:52:17.678 DEBUG 9808 --- [  XNIO-1 task-1] c.w.a.r.CustomAuditEventRepository       : Enter: add() with argument[s] = AuditEvent [timestamp=2020-12-06T19:52:17.629772Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 192.168.2.100; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]
2020-12-06 16:52:17.685 DEBUG 9808 --- [  XNIO-1 task-1] c.w.a.r.CustomAuditEventRepository       : Exit: add() with result = null
2020-12-06 16:52:17.685 DEBUG 9808 --- [  XNIO-1 task-1] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2020-12-06 16:52:17.685 DEBUG 9808 --- [  XNIO-1 task-1] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(625374968<open>)]
2020-12-06 16:52:17.691 DEBUG 9808 --- [  XNIO-1 task-1] o.s.orm.jpa.JpaTransactionManager        : Closing JPA EntityManager [SessionImpl(625374968<open>)] after transaction
2020-12-06 16:52:17.698 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is anonymous); redirecting to authentication entry point

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:123)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationCodeGrantFilter.doFilterInternal(OAuth2AuthorizationCodeGrantFilter.java:146)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:114)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:160)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SessionRestoringHandler.handleRequest(SessionRestoringHandler.java:119)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-12-06 16:52:17.705 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.a.ExceptionTranslationFilter     : Calling Authentication entry point.
2020-12-06 16:52:17.764 DEBUG 9808 --- [  XNIO-1 task-1] .m.m.a.ExceptionHandlerExceptionResolver : Using @ExceptionHandler com.works.app.web.rest.errors.ExceptionTranslator#handleAuthentication(AuthenticationException, NativeWebRequest)
2020-12-06 16:52:17.862  WARN 9808 --- [  XNIO-1 task-1] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2020-12-06 16:52:17.996 DEBUG 9808 --- [  XNIO-1 task-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Found 'Content-Type:application/problem+json' in response
2020-12-06 16:52:18.124 DEBUG 9808 --- [  XNIO-1 task-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Writing [https://www.jhipster.tech/problem/problem-with-message{401, Unauthorized, Full authentication is req (truncated)...]
2020-12-06 16:52:18.146 DEBUG 9808 --- [  XNIO-1 task-1] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@14ec19b9
2020-12-06 16:52:18.228  WARN 9808 --- [  XNIO-1 task-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource]
2020-12-06 16:52:18.229 DEBUG 9808 --- [  XNIO-1 task-1] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2020-12-06 16:55:49.635  INFO 9808 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-12-06 16:56:00.004 DEBUG 9808 --- [nfoReplicator-0] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'spring.application.name' in PropertySource 'configurationProperties' with value of type String
2020-12-06 16:56:00.005 DEBUG 9808 --- [nfoReplicator-0] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'spring.cloud.config.name' in PropertySource 'configurationProperties' with value of type String
2020-12-06 16:56:00.006 DEBUG 9808 --- [nfoReplicator-0] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'spring.cloud.config.profile' in PropertySource 'configurationProperties' with value of type String
2020-12-06 16:56:00.006 DEBUG 9808 --- [nfoReplicator-0] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'spring.cloud.config.label' in PropertySource 'configurationProperties' with value of type String
2020-12-06 16:56:00.012  INFO 9808 --- [nfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8761/config
2020-12-06 16:56:00.012 DEBUG 9808 --- [nfoReplicator-0] o.s.web.client.RestTemplate              : HTTP GET http://localhost:8761/config/products/dev/master
2020-12-06 16:56:00.018 DEBUG 9808 --- [nfoReplicator-0] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2020-12-06 16:56:00.331 DEBUG 9808 --- [nfoReplicator-0] o.s.web.client.RestTemplate              : Response 200 OK
2020-12-06 16:56:00.331 DEBUG 9808 --- [nfoReplicator-0] o.s.web.client.RestTemplate              : Reading to [org.springframework.cloud.config.environment.Environment]
2020-12-06 16:56:00.333  INFO 9808 --- [nfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=products, profiles=[dev], label=master, version=null, state=null
2020-12-06 16:56:00.333 DEBUG 9808 --- [nfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Environment products has 1 property sources with 4 properties.```

**Comment by julillosamaral** [comment] 2020-12-06 20:53
A bit more of information, it seems that the Authorization header is removed in the gateway.
This image is the interception of the request for the kotlin version:
![image](https://user-images.githubusercontent.com/979882/101291982-5c480c80-37eb-11eb-8ebe-ec5241bd299b.png)

The next image is the version for the java version:
![image](https://user-images.githubusercontent.com/979882/101292048-d7112780-37eb-11eb-8192-9359e1078f4c.png)


I'll continue down this path checking the differences between both gateways. If someone know what the issue is please let me know and I'll finish the fix!

**Comment by sendilkumarn** [comment] 2021-03-03 18:16
Thanks @andrzej-polanowski-emerge  & @julillosamaral  for the issue. I am sorry it took a while to come back to this issue, but did you find the solution?

**Comment by julillosamaral** [comment] 2021-03-03 21:05
So, I finally had to use the Gateway in Java because it was the only way I made it work.
Having it in Kotlin made me loose the Authorization header as I stated in previous message.

My theory is that the issue is caused by Netflix netflix-zuul having some issue with Kotlin, I know there's some configuration to avoid this issue and it works correctly for Java. The issue is https://github.com/spring-cloud/spring-cloud-netflix/issues/3126 and it seems it's in place.

Sorry I didn't find anything else and haven't been able to work on this issues but we have a lot of work right now!

**Comment by sendilkumarn** [comment] 2021-03-03 21:28
Thanks @julillosamaral I was able to demo things a couple of weeks before without any issue (but I did not use OAuth2). I think the problem will be in the spring-security area. 

Let me check this, when I have some time. Again thanks for the input and raising the issue.

**Comment by julillosamaral** [comment] 2021-03-04 13:09
We found the problem using OAuth2 with keycloak (maybe without it the issue persists). Using other type of authentication we didn't have the problem and everything was working really well!

**Closed** 2021-05-01 23:44 UTC
Labels: $$ bug-bounty 💸, $100
