### ISSUE TITLE
Improve generated gradle build script

### ISSUE THREAD

**Issue by soberich** [jhipster/jhipster-kotlin#32] opened 2018-06-05 21:14 UTC
Hi, 
To start with..
the generated build script is simply not compileable because of the version in properties file which is 
`2.0.0-20180313.135554-7` and some other stuff.
it is already `2.0.8` available.. Ok, it is not the latest but Why is it the snapshot with `20180313.135554......` which is not very great to put in publicly available template (I mean should this not be always a stable one?)
The script
```groovy
import org.gradle.internal.os.OperatingSystem

buildscript {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "http://repo.spring.io/plugins-release" }
        maven { url "https://plugins.gradle.org/m2/" }
        // TODO To remove after final Spring Boot 2 release
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://dl.bintray.com/jhipster/maven" }
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${spring_boot_version}"
        classpath "io.spring.gradle:propdeps-plugin:0.0.9.RELEASE"
        classpath "gradle.plugin.org.detoeuf:swagger-codegen-plugin:1.7.4"
        classpath "gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.4.17"
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30'
        classpath 'org.jetbrains.kotlin:kotlin-allopen:1.2.30'
        //jhipster-needle-gradle-buildscript-dependency - JHipster will add additional gradle build script plugins here
    }
}

plugins {
    id "org.sonarqube" version "2.6.2"
    id "net.ltgt.apt-eclipse" version "0.15"
    id "net.ltgt.apt-idea" version "0.15"
    id "net.ltgt.apt" version "0.15"
    id "io.spring.dependency-management" version "1.0.3.RELEASE"
    id "com.moowork.node" version "1.2.0"
    //jhipster-needle-gradle-plugins - JHipster will add additional gradle plugins here
}

apply plugin: 'java'
sourceCompatibility=1.8
targetCompatibility=1.8
// Until JHipster supports JDK 9
assert System.properties['java.specification.version'] == '1.8'

apply plugin: 'maven'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: 'propdeps'
apply plugin: 'com.moowork.node'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'idea'

dependencyManagement {
  imports {
    mavenBom 'io.github.jhipster:jhipster-dependencies:' + jhipster_dependencies_version
    //jhipster-needle-gradle-dependency-management - JHipster will add additional dependencies management here
  }
}

defaultTasks 'bootRun'

group = 'com.psg.lap'
version = '0.0.1-SNAPSHOT'

description = ''

bootWar {
   mainClassName = 'com.psg.lap.LapApp'
}

war {

}

springBoot {
    mainClassName = 'com.psg.lap.LapApp'
    buildInfo()
}

if (OperatingSystem.current().isWindows()) {
    task pathingJar(type: Jar) {
        dependsOn configurations.runtime
        appendix = 'pathing'

        doFirst {
            manifest {
                attributes 'Class-Path': configurations.runtime.files.collect {
                    it.toURI().toURL().toString().replaceFirst(/file:\/+/, '/').replaceAll(' ', '%20')
                }.join(' ')
            }
        }
    }

    bootRun {
        dependsOn pathingJar
        doFirst {
            classpath += files("$buildDir/classes/java/main", "$buildDir/resources/main", pathingJar.archivePath)
        }
    }
}

test {
    exclude '**/CucumberTest*'

    // uncomment if the tests reports are not generated
    // see https://github.com/jhipster/generator-jhipster/pull/2771 and https://github.com/jhipster/generator-jhipster/pull/4484
    // ignoreFailures true
    reports.html.enabled = false
}

task testReport(type: TestReport) {
    destinationDir = file("$buildDir/reports/tests")
    reportOn test
}


apply from: 'gradle/docker.gradle'
apply from: 'gradle/sonar.gradle'
apply from: 'gradle/liquibase.gradle'
apply from: 'gradle/mapstruct.gradle'
apply from: 'gradle/swagger.gradle'
apply from: 'gradle/kotlin.gradle'
//jhipster-needle-gradle-apply-from - JHipster will add additional gradle scripts to be applied here

if (project.hasProperty('prod')) {
    apply from: 'gradle/profile_prod.gradle'
} else {
    apply from: 'gradle/profile_dev.gradle'
}

if (project.hasProperty('graphite')) {
    apply from: 'gradle/graphite.gradle'
}

if (project.hasProperty('prometheus')) {
    apply from: 'gradle/prometheus.gradle'
}

if (project.hasProperty('zipkin')) {
    apply from: 'gradle/zipkin.gradle'
}

configurations {
    providedRuntime
    compile.exclude module: "spring-boot-starter-tomcat"
}

repositories {
    mavenLocal()
    jcenter()
    // TODO To remove after final Spring Boot 2 release
    maven { url "https://repo.spring.io/milestone" }
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://dl.bintray.com/jhipster/maven" }
    //jhipster-needle-gradle-repositories - JHipster will add additional repositories
}

dependencies {
    // TODO To remove after final Spring Boot 2 release
    compile "javax.xml.bind:jaxb-api"
    compile "org.springframework.boot:spring-boot-starter-cache"
    compile "io.github.jhipster:jhipster"
    compile "io.dropwizard.metrics:metrics-core"
    compile "io.dropwizard.metrics:metrics-jcache"
    compile "io.dropwizard.metrics:metrics-json"
    compile "io.dropwizard.metrics:metrics-jvm"
    compile "io.dropwizard.metrics:metrics-servlet"
    compile "io.dropwizard.metrics:metrics-servlets"
    compile "net.logstash.logback:logstash-logback-encoder"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-json-org"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-hppc"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    compile "com.fasterxml.jackson.datatype:jackson-datatype-hibernate5"
    compile "com.fasterxml.jackson.core:jackson-annotations"
    compile "com.fasterxml.jackson.core:jackson-databind"
    compile "com.fasterxml.jackson.module:jackson-module-afterburner"
    compile "com.ryantenney.metrics:metrics-spring"
    compile "javax.cache:cache-api"
    compile "org.hibernate:hibernate-core"
    compile "com.zaxxer:HikariCP"
    compile "org.apache.commons:commons-lang3"
    compile "commons-io:commons-io"
    compile "javax.transaction:javax.transaction-api"
    compile "org.ehcache:ehcache"
    compile "org.hibernate:hibernate-jcache"
    compile "org.hibernate:hibernate-entitymanager"
    compile "org.hibernate:hibernate-envers"
    compile "org.hibernate.validator:hibernate-validator"
    compile "org.liquibase:liquibase-core"
    compile "com.mattbertolini:liquibase-slf4j"
    compile "org.springframework.boot:spring-boot-loader-tools"
    compile "org.springframework.boot:spring-boot-starter-mail"
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile ("org.springframework.boot:spring-boot-starter-actuator") {
        exclude module: 'micrometer-core'
    }
    compile "org.springframework.boot:spring-boot-starter-aop"
    compile "org.springframework.boot:spring-boot-starter-data-jpa"
    compile "org.springframework.boot:spring-boot-starter-data-elasticsearch"
    // needed to get around elasticsearch stacktrace about jna not found
    // https://github.com/elastic/elasticsearch/issues/13245
    compile "net.java.dev.jna:jna"
    compile "org.springframework.boot:spring-boot-starter-security"
    compile ("org.springframework.boot:spring-boot-starter-web") {
        exclude module: 'spring-boot-starter-tomcat'
    }
    compile "org.springframework.boot:spring-boot-starter-undertow"
    compile "org.springframework.boot:spring-boot-starter-thymeleaf"
    compile "org.zalando:problem-spring-web"
    compile "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client"
    compile "org.springframework.cloud:spring-cloud-starter-config"
    compile "org.springframework.cloud:spring-cloud-spring-service-connector"
    compile "org.springframework.security:spring-security-config"
    compile "org.springframework.security:spring-security-data"
    compile "org.springframework.security:spring-security-web"
    compile "io.jsonwebtoken:jjwt"
    compile ("io.springfox:springfox-swagger2") {
        exclude module: 'mapstruct'
    }
    compile "io.springfox:springfox-bean-validators"
    compile "mysql:mysql-connector-java"
    compile "org.mapstruct:mapstruct-jdk8:${mapstruct_version}"
    compile "org.apache.httpcomponents:httpclient"
    compile "org.springframework.social:spring-social-security"
    compile "org.springframework.social:spring-social-google"
    compile "org.springframework.social:spring-social-facebook"
    compile "org.springframework.social:spring-social-twitter"
    testCompile "com.jayway.jsonpath:json-path"
    testCompile ("org.springframework.boot:spring-boot-starter-test") {
        exclude group: 'com.vaadin.external.google', module: 'android-json'
    }
    testCompile "org.springframework.security:spring-security-test"
    testCompile "org.springframework.boot:spring-boot-test"
    testCompile "org.assertj:assertj-core"
    testCompile "junit:junit"
    testCompile "org.mockito:mockito-core"
    testCompile "com.mattbertolini:liquibase-slf4j"
    testCompile "org.hamcrest:hamcrest-library"
    optional ("org.springframework.boot:spring-boot-configuration-processor") {
        exclude group: 'com.vaadin.external.google', module: 'android-json'
    }
    //jhipster-needle-gradle-dependency - JHipster will add additional dependencies here
}

task cleanResources(type: Delete) {
    delete 'build/resources'
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.6'
}

task stage(dependsOn: 'bootWar') {
}

if (project.hasProperty('nodeInstall')) {
    node {
        version = "${node_version}"
        npmVersion = "${npm_version}"
        yarnVersion = "${yarn_version}"
        download = true
    }
}

compileJava.dependsOn processResources
processResources.dependsOn cleanResources,bootBuildInfo
bootBuildInfo.mustRunAfter cleanResources

```

I am not sure that should have been ever released as the quality of generated script is somewhat.. Not trying to be an ass, just simply it is Honestly somewhat.. 
Is it some kind of automatic templating so that even template wi not what some has manually wrote? If so, it's understandable that sometimes it would be not great if not - not understandable...
`compile` and `runtime` configs are deprecated. Gradle provided native `BOM` support now as well as `annotationProcessor` configuration (if not even mention of Kotlin scripts). `buildscript { }` in this particular configuration can be omitted (and should be, I belevive for the sake of modernize the approach as this was introduced in Gradle 2.12!! (years ago))

I would gladly make a PR later (I will push myself to do so) , can you tell me it this is relevant? Is this repo is alive and will further be in development? Do you wish to keep Groovy or use Kotlin (pref) ? And why the generated project is like half of Kotlin and another half is plain Java?

#### Edit 
Also `org.detoeuf.swagger-codegen` is deprecated

**Comment by sendilkumarn** [comment] 2018-06-08 10:00
> 2.0.0-20180313.135554-7 and some other stuff.

Agree but only in that version blueprint is working so, it is kept in that. There are some issues with blueprint that makes it completely not usable. 

> I would gladly make a PR later (I will push myself to do so) , can you tell me it this is relevant?

Thanks, but wait for another week, I hope the [issue](https://github.com/jhipster/generator-jhipster/issues/7238) with blueprint will be fixed. Pinging @deepu105  here

> Is this repo is alive and will further be in development? 

It is very much in the plan. 

> Do you wish to keep Groovy or use Kotlin (pref) ? 

I would love to use Kotlin, but the problem is that you have to rewrite the gradle files from the main generator and change it everytime they are changing, that was the only problem with that.

> And why the generated project is like half of Kotlin and another half is plain Java?

Exactly the same problem as mentioned above, `JHipster` is a fast moving project and tracking all the changes and pushing them into this project is really problematic. There are some excellent points discussed [here](https://github.com/jhipster/jhipster-kotlin/issues/3)

**Comment by sendilkumarn** [comment] 2018-06-11 11:00
Closing this issue, feel free to add in your comment if you have any

**Closed by sendilkumarn** 2018-06-11 11:00 UTC

**Comment by soberich** [comment] 2018-06-19 23:01
Hi, @sendilkumarn @jkutner @mraible @amr @jmirc 
I have pushed a proposed example https://github.com/soberich/jhipster-gradle-kotlin-dsl
Main stuff:

0. It starts to work with Gradle 4.**9**+ (uses lazy tasks)
1. Precompiled scripts allow us to truly externalize inclusion logic to those plugins which looks and feels naturally as if they were inclusions like `apply from` but they are created on-the-fly and applyed by dependency substitution with `pluginManagement` (inclusion with `apply from` in NOT recommended by gradle developers) 
2. Any project module build script may now look as clean as
```kotlin
plugins {
    java
    id("tech.jhipster.jpa")
    id("tech.jhipster.spring-boot")
    id("tech.jhipster.sonar")
}
```
and nothing else.. Jhipster may chose to create own gradle plugins "local library" (which will be distributed with every jhipster generated app according to which options user chose during set up) so, these plugins will serve same purpose as `apply from..` inclusions now but in a very optimized way as each plugin you will polish will its perfect form.
    3. Classpath jar probably may be substituted with https://github.com/viswaramamoorthy/gradle-util-plugins
which I did here though I did run everything on Windows I did not test whether it works or not.
Anyway all tests run fune.
Please see 
https://github.com/soberich/jhipster-gradle-kotlin-dsl/commit/91b606519fd019ebca8505ad2a4c7aa4527f91ba
