### ISSUE TITLE
Use build.gradle.kts for Gradle

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-kotlin#231] opened 2020-05-03 19:33 UTC
## Overview of the issue

I think it'd be a cool feature to use Kotlin for the `build.gradle` file.

## Motivation for or Use Case

It might not be a huge value-add, but I've enjoyed working with Kotlin in my Gradle build in a recent project.

## Related issues

If you agree this is a good idea, I can create an issue in the main JHipster project to add a bug bounty to it. I'd also be happy to help more with this project. Is it possible to document how you go about updating it for new JHipster releases?

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment] 2020-05-03 20:32
You would like to do it for the main generator too or just the kotlin blueprint or try it here and eventually do it in the main generator?

**Comment by mraible** [comment] 2020-05-03 21:48
I think it makes sense to only do it for KHipster. It took me a while to figure out how to use it. @bsautel was a huge help! https://github.com/node-gradle/gradle-node-plugin/issues/98

**Comment by sendilkumarn** [comment] 2020-05-04 07:37
Yeah I have been thinking about this for a while. The main problem is that we have to change the Gradle files based on the master changes. I am not sure whether it is worth the effort. 

Can we partially use Gradle file in Kotlin?

**Comment by sendilkumarn** [comment] 2020-06-09 06:18
Started the initial work at here https://github.com/sendilkumarn/khipster-gradle-kts-migration/pull/1 

@atomfrede interested to expand it further (I am not an Gradle expert 👍 so any help / review is much appreciated).

**Comment by jonasbark** [comment] 2020-09-24 21:11
@sendilkumarn you closed the PR yourself - why was that?

**Comment by sendilkumarn** [comment] 2020-09-24 21:22
@jonasbark did not have time to invest in it. Please feel free to revive the PR, if you are interested :)

**Comment by kevin-madhu** [comment] 2020-09-25 04:16
@sendilkumarn I'm interested.

**Comment by jonasbark** [comment] 2020-09-25 06:01
@kevin-madhu want to do it? Otherwise I'll invest some time over the weekend

**Comment by kevin-madhu** [comment] 2020-09-25 06:37
@jonasbark I want to do it. I'm new to jhipster and jhipster-kotlin generators and this looks like something I can get done and so it's interesting for me. I've started exploring it right now and if I hit a wall, I'll let you know by tomorrow so that you can take it up.

**Comment by kevin-madhu** [comment] 2020-09-26 18:56
@sendilkumarn @mraible @jonasbark
Hi everyone,
  Here's the initial form of solution I could come up with. It seems to be a pretty big diversion or rearrangement rather, than what's already exists. Basically, when I was exploring the Kotlin DSL offered by Gradle, I came across an issue which will limit us from splitting the Gradle build file like it used to be when using Groovy DSL. The issue https://github.com/gradle/gradle/issues/1262 looks similar to the issue I came across. Also, I assume @sendilkumarn  came across this issue because I saw that the apply statements which were targeted at applying the other gradle/*.gradle.kts were all commented out. After some digging around I came across Precompiled Plugins in Gradle (https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins) which will let us do exactly what we want and so I ended up using it. I also moved much of the code from build.gradle.kts file to those precompiled plugins. The names of those precompiled plugins were postfixed with "-khipster", so that they're easily identifiable and not confused with standard plugin notations offered by Gradle itself. You can view the changes I made, here:
1) https://github.com/kevin-madhu/khipster-gradle-kts-migration/tree/gradle-compiled-plugin-experiment (Branch)
2) https://github.com/kevin-madhu/khipster-gradle-kts-migration/commit/0cde5a7c9d5a54b167c5fbef39fc89fe66198a66 (Commit)

The build probably fails, there's more work to be done and it's also yet to be thoroughly tested. But, I wanted to know everyone's views on this before I continued and put in more effort. Please take a look at it and let me know. Thanks

**Comment by kevin-madhu** [comment] 2020-09-27 07:21
As a side note, one advantage of moving much of the logic into these plugins from build.gradle.kts is that later on when this gets released and tested and saturates over time, maybe we could completely extract everything out of khipster project into an independent Khipster Gradle plugin (maybe a Jhipster one too).

**Comment by sendilkumarn** [comment] 2020-09-30 22:02
@kevin-madhu Thanks a lot for exploring this! I haven't done many experiments with pre-compiled plugins in Gradle. 

My only question is, if we go in the pre-compiled direction, can the end user customise the build? 

@atomfrede do you have any thoughts here about using pre-compiled plugins?

**Comment by kevin-madhu** [comment] 2020-10-01 04:36
@sendilkumarn What kind of build customizations are you talking about? Can you give me a bit more description? The versions of dependencies can always be overridden by putting them in build.gradle.kts I guess. Also, people who want to add more tasks and so on could also do it in build.gradle.kts or inside buildSrc. I can come up with proper documentation for how these kinds of things could be done, but I need more information as to how users may customize these.

**Comment by atomfrede** [comment] 2020-10-01 05:40
I always wanted to start a jhipster gradle plugin, such that the generated configuration e.g. only applies two or three plugins depending on the selected configuration. But the problem is, when there is an error/bug or so we must release a new plugin version and a new generator. With the current state having all used plugins directly in use version updates or workarounds are quite easy for users.

**Comment by kevin-madhu** [comment] 2020-10-01 06:10
@atomfrede I'm pretty new to Jhipster and yeoman generators in general. Still in the process of learning. The workarounds are something we could solve for the users by good documentation and by providing flexible configuration options I guess. But the release part is still an issue. How about we come up with a new command "jhipster gradle-plugin-upgrade" or something, like "jhipster upgrade" which takes care of these kinds of upgrades when a new version is available, instead of having to release new generator everytime there's a new version of plugin released?

**Comment by kevin-madhu** [comment] 2020-10-01 11:37
@atomfrede I'm pretty new to Jhipster and yeoman generators in general. Still in the process of learning. The workarounds are something we could solve for the users by good documentation and by providing flexible configuration options I guess. But the release part is still an issue. How about we come up with a new command "jhipster gradle-plugin-upgrade" or something, like "jhipster upgrade" which takes care of these kinds of upgrades when a new version is available, instead of having to release new generator everytime there's a new version of plugin released?

One thing to note is that - even currently, if there's an issue with the build part, we'll need to release a new generator anyways. In my opinion, with the existence of plugins even without the existence of any commands like I mentioned, it just takes a bit more work for the developers to release a new generator with the new plugin version, and for the user it shouldn't matter because in their case they anyways had to upgrade generator version with or without the existence of independent plugins because of the bug. So a simple solution is just to synchronize new plugin version releases along with the releases of a new generator version. Or do we completely abandon the plugin idea? I could still continue with the precompiled plugin line I was working on because they do not have these limitations as they're part of the project.

@atomfrede Between, I think you've confused gradle precompiled plugins with gradle plugins - precompiled plugins are distributed along with the project just like the normal gradle files are being distributed now.

**Comment by sendilkumarn** [comment] 2021-03-03 18:06
Closing this, since there is no active development here. If anyone is interested please feel free to comment here. Thanks.

**Closed by sendilkumarn** 2021-03-03 18:06 UTC
Labels: $$ bug-bounty 💸, $200

**Comment by kevin-madhu** [comment] 2021-03-03 18:13
@sendilkumarn I'm still up for it. Got a little bit busy. Also I didn't get response on my query.

**Comment by sendilkumarn** [comment] 2021-03-03 18:21
> @atomfrede I'm pretty new to Jhipster and yeoman generators in general. Still in the process of learning. The workarounds are something we could solve for the users by good documentation and by providing flexible configuration options I guess. But the release part is still an issue. How about we come up with a new command "jhipster gradle-plugin-upgrade" or something, like "jhipster upgrade" which takes care of these kinds of upgrades when a new version is available, instead of having to release new generator everytime there's a new version of plugin released?

IMO, let us not go towards the pre-compiled gradle plugins direction as the first step. Let us first convert the existing groovy scripts to kotlin scripts. The next step will be exploring pre-compile gradle plugins that is used both in the JHipster and KHipster. WDYT?

**Comment by kevin-madhu** [comment] 2021-03-03 18:34
Sure, we could do that. 👍 In that case,  I'll reopen the issue when I've  worked it out.

**Comment by sendilkumarn** [comment] 2021-03-03 21:29
Awesome! Let me assign it to you. 🎉
